version: "3.2"

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_USER: Admin
      POSTGRES_DB: Load
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    restart: always